const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  STATUS_VERIFY: "STATUS_VERIFY",
  // //admin
  // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILDED: "FETCH_GENDER_FAILDED",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCEScontentHTMLS",
  FETCH_POSITION_FAILDED: "FETCH_POSITION_FAILDED",
  FETCH_ROLEID_SUCCESS: "FETCH_ROLEID_SUCCESS",
  FETCH_ROLEID_FAILDED: "FETCH_ROLEID_FAILDED",
  //admin-user-information
  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAILDED: "SAVE_USER_FAILDED",
  //view-edit-delete-in table
  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILDED: "FETCH_ALL_USERS_FAILDED",

  FETCH_DELETE_USER_SUCCESS: "FETCH_DELETE_USER_SUCCESS",
  FETCH_DELETE_USER_FAILDED: "FETCH_DELETE_USER_FAILDED",

  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILDED: "UPDATE_USER_FAILDED",

  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAILDED: "FETCH_TOP_DOCTOR_FAILDED",

  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAILDED: "FETCH_ALL_DOCTOR_FAILDED",

  SAVE_OBJECT_DOCTOR_SUCCESS: "SAVE_OBJECT_DOCTOR_SUCCESS",
  SAVE_OBJECT_DOCTOR_FAILDED: "SAVE_OBJECT_DOCTOR_FAILDED",

  HANDLE_FIND_DOCTOR_DOCTOR_SUCCESS: "HANDLE_FIND_DOCTOR_DOCTOR_SUCCESS",
  HANDLE_FIND_DOCTOR_DOCTOR_FAILDED: "HANDLE_FIND_DOCTOR_DOCTOR_FAILDED",

  FETCH_DETAIL_INFOR_DOCTOR_SUCCESS: "FETCH_DETAIL_INFOR_DOCTOR_SUCCESS",
  FETCH_DETAIL_INFOR_DOCTOR_FAILDED: "FETCH_DETAIL_INFOR_DOCTOR_FAILDED",

  FETCH_ALLCODE_SCHEDULE_TIME_DOCTOR_SUCCESS: "FETCH_ALLCODE_SCHEDULE_TIME_DOCTOR_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_TIME_DOCTOR_FAILDED: "FETCH_ALLCODE_SCHEDULE_TIME_DOCTOR_FAILDED",

  POST_SCHEDULE_TIME_DOCTOR_SUCCESS: "POST_SCHEDULE_TIME_DOCTOR_SUCCESS",
  POST_SCHEDULE_TIME_DOCTOR_FAILDED: "POST_SCHEDULE_TIME_DOCTOR_FAILDED",
  
  GET_SCHEDULE_TIME_DOCTOR_SUCCESS: "GET_SCHEDULE_TIME_DOCTOR_SUCCESS",
  GET_SCHEDULE_TIME_DOCTOR_FAILDED: "GET_SCHEDULE_TIME_DOCTOR_FAILDED",

  FETCH_REQUIRED_DOCTOR_INFOR_START: "FETCH_REQUIRED_DOCTOR_INFOR_START",
  FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: "FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS",
  FETCH_REQUIRED_DOCTOR_INFOR_FAILDED: "FETCH_REQUIRED_DOCTOR_INFOR_FAILDED",

  //getBesideInfor
  FETCH_BESIDE_INFOR_INFOR_SUCCESS: "FETCH_BESIDE_INFOR_INFOR_SUCCESS",
  FETCH_BESIDE_INFOR_INFOR_FAILDED: "FETCH_BESIDE_INFOR_INFOR_FAILDED",
  //
  GET_DOCTOR_INFOR_APPIONTMENT_SUCCESS: "GET_DOCTOR_INFOR_APPIONTMENT_SUCCESS",
  GET_DOCTOR_INFOR_APPIONTMENT_FAILDED: "GET_DOCTOR_INFOR_APPIONTMENT_FAILDED",
  //specialtys
  HANDLE_SAVE_SPECIALTY_SUCCESS: "HANDLE_SAVE_SPECIALTY_SUCCESS",
  HANDLE_SAVE_SPECIALTY_FAILDED: "HANDLE_SAVE_SPECIALTY_FAILDED",

});

export default actionTypes;
